TARGET = XK-1500
APP_NAME = 
XCC_FLAGS = -g -O3
USED_MODULES = module_uart_fast_rx module_uart_fast_tx

# Use the latest 1v* version of module_xmos_common
-include ../module_xcommon/build/Makefile.common
-include ../../xcommon/module_xcommon/build/Makefile.common
